global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'amenbank-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:

  - job_name: 'spring-backend'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
    scrape_interval: 15s

  - job_name: 'chatbot'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['chatbot:8000']
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
